### ISSUE TITLE
'js' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by jakobrosenberg** [user896724/sve#1]
Tried cloning the repo and ran ``npm i`` and ``npm start`` after which I got the error:

``'js' is not recognized as an internal or external command``

Any chance there's a dependency missing?

**Comment by user896724** [comment]
Ah, this is just because I alias `js` to `nodejs`and forget it's not there by default.  Thanks for reporting,  I'll update the script.

**Comment by user896724** [comment]
Oh it looks like I already did :)
