### ISSUE TITLE
How does Svelte-view-engine handle async data?

### ISSUE THREAD

**Issue by jakobrosenberg** [user896724/sve#2]
```html
<script>
  const dataPromise = myApi(resource)
</script>
  
{#await dataPromise then data}
  Data loaded: {JSON.stringify(data)}
{/await}
```

**Comment by user896724** [comment]
Hmm good question, I haven't used `{#await}` yet myself so haven't thought about how it would work with SSR etc.  I would have to see a more concrete use case to figure it out, but my first instinct would be not to use `{#await}` at all and resolve the promise either serverside, in the route, and pass the resolved value to `render()`; or on the client, in `onMount` or in response to an event.

**Comment by user896724** [comment]
Promises are not awaited with SSR - the await block is rendered.  There is an open issue in svelte to support async rendering - https://github.com/sveltejs/svelte/issues/958, which if it gets implemented I'll probably mirror in svelte-view-engine.  So #await works fine currently, it just only awaits on the client.
